sudo: false
language: "python"
python:
  - "3.6"
cache: "pip"
addons:
  apt:
    packages:
      - "libimage-exiftool-perl"
install:
  - "pip install -e .[tests,release]"
script:
  - "pylama"
  - "which foto"
  - "foto --version"
  - "foto --help"
  - "py.test --cov-report="
after_success:
  - "coveralls"
  - "git config user.name 'Honza Javorek'"
  - "git config user.email 'mail@honzajavorek.cz'"
  - "python setup.py publish"  # requires GH_TOKEN, PYPI_USERNAME, PYPI_PASSWORD
