info_basename: album.yml
index_basename: .arrange
command: subl -n -w
photo_exts: [jpg, jpeg, png, raw]
video_exts: [mov, avi, mp4, mpg, 3gp]
audio_exts: [amr]
# media_exts: [... all above ...] (automatically compiled and added)
rubbish: [feed.rss, Thumbs.db, .arrange, .DS_Store, Picasa.ini, info.txt, 'View Online.url']

yaml:
  indent: 2
  allow_unicode: true
  default_flow_style: false
  default_style: ''

geocoding:
  # key: FOTO_GEOCODING_API_KEY (taken from environment variable)
  language: cs

converting:
  jpg:
    command: jpegtran
    params: -optimize -copy all {in_filename}
    out_ext: jpg
    stdout: true

  mov-panasonic-dmc-fz8:
    command: ffmpeg
    params: |
      -i {in_filename} -vcodec libx264 -crf 25.5 -acodec libmp3lame -ab 64k -ac 1 -ar 16000 -aspect 4:3 -r 30 -y -f mp4 {out_filename}
    out_ext: mp4
    export_metadata: yes

  mp4-panasonic-dmc-tz80:
    command: ffmpeg
    params: |
      -i {in_filename} -y -c:v libx264 -crf 24 -preset slow -profile:v high -f mp4 -c:a aac -b 120k {out_filename}
    out_ext: mp4

  mov-apple-iphone-se:
    command: ffmpeg
    params: |
      -i {in_filename} -y -c:v libx264 -crf 24 -preset slow -profile:v high -f mp4 -c:a aac -b 120k {out_filename}
    out_ext: mp4

  mp4-motorola-xt1069:
    command: ffmpeg
    params: |
      -i {in_filename} -y -c:v libx264 -crf 24 -preset slow -profile:v high -f mp4 -c:a aac -b 120k {out_filename}
    out_ext: mp4

  mkv:
    command: ffmpeg
    params: |
      -i {in_filename} -y -vcodec copy -acodec copy -f mp4 {out_filename}
    out_ext: mp4

  avi:
    command: ffmpeg
    params: |
      -i {in_filename} -y -vcodec copy -acodec copy -f mp4 {out_filename}
    out_ext: mp4

  3gp:
    command: ffmpeg
    params: -i {in_filename} -y -f mp4 {out_filename}
    out_ext: mp4

  amr:
    command: ffmpeg
    params: -i {in_filename} -y -f mp3 {out_filename}
    out_ext: mp3
